version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install

  checkstyle:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run Checkstyle and generate HTML report
          command: |
            mvn checkstyle:checkstyle &&  # Exécute Checkstyle
            mvn checkstyle:checkstyle-report  # Génére le rapport HTML
      - store_artifacts:
          path: target/site
          destination: checkstyle-report

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run tests with Maven
          command: mvn test
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

  checkstyle_workflow:
    jobs:
      - checkstyle
