version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install

  checkstyle:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Checkstyle Status JSON
          command: |
            if grep -q "<error" target/site/checkstyle-result.xml; then
              echo '{"status": "échoué"}' > checkstyle-status.json
            else
              echo '{"status": "réussi"}' > checkstyle-status.json
            fi
      - store_artifacts:
          path: checkstyle-status.json
          destination: checkstyle-status
      - run:
          name: Remove all files from gh-pages branch
          command: |
            # Change to gh-pages branch
            git checkout --orphan gh-pages
            git rm -rf .  # Remove all files from gh-pages branch
            git commit -m "Remove all files from gh-pages"
            git push origin gh-pages --force  # Force push the empty state to gh-pages
      - run:
          name: Commit Checkstyle Status JSON to GitHub Pages
          command: |
            git checkout gh-pages
            git add checkstyle-status.json  # Add only the checkstyle-status.json
            git commit -m "Update Checkstyle status"
            git push origin gh-pages  # Push the updated file to gh-pages

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run tests with Maven
          command: mvn test
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

  checkstyle_workflow:
    jobs:
      - checkstyle
