version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install

  checkstyle:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run tests with Maven
          command: mvn test
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - checkstyle:
          requires:
            - build
      - test:
          requires:
            - checkstyle