name: Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html

      - name: Generate Checkstyle Badge
        run: |
          if grep -q "<error" target/site/checkstyle-result.xml; then
            echo "Checkstyle: Failed" > checkstyle-badge.txt
          else
            echo "Checkstyle: Passed" > checkstyle-badge.txt
          fi

      - name: Commit Checkstyle Badge to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add checkstyle-badge.txt
          git commit -m "Update Checkstyle Badge"
          git push origin gh-pages
