name: Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run:
            name: Run Checkstyle
            command: mvn checkstyle:check
      - run:
            name: Generate Checkstyle Status JSON
            command: |
              if grep -q "<error" target/site/checkstyle-result.xml; then
                echo '{"status": "échoué"}' > checkstyle-status.json
              else
                echo '{"status": "réussi"}' > checkstyle-status.json
              fi


      - name: Display Checkstyle Status JSON
        run: cat checkstyle-status.json



      - name: Commit Checkstyle Badge to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout gh-pages || git checkout --orphan gh-pages
          git add checkstyle-status.json
          git commit -m "Update Checkstyle status"
          git push origin gh-pages
