name: Generate and Deploy Checkstyle Status

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_checkstyle_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Generate Checkstyle Status JSON
        run: |
          if grep -q "<error" target/site/checkstyle-result.xml; then
            echo '{"status": "échec"}' > checkstyle-status.json
          else
            echo '{"status": "réussi"}' > checkstyle-status.json
          fi

      - name: Commit Checkstyle Status to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./checkstyle-status.json
          destination_dir: checkstyle-status
